### ISSUE TITLE
bs Default Values Documentation Contradicts Function Specification

### ISSUE THREAD

**Issue by DarioS** [ryantibs/best-subset#12]
For `k`, the documentation explains "... 1:min(n-1,p,200) for models with intercept and 1:min(n,p,200) for models without it." but the function definition specifies `k=0:min(nrow(x)-intercept,ncol(x))`. Can these be made consistent?

**Comment by ryantibs** [comment]
OK, thanks for pointing this out.  I've fixed it now: the default range for k is now k=0:min(nrow(x)-intercept,ncol(x),200).
