### ISSUE TITLE
Unable to Install in Debian 8

### ISSUE THREAD

**Issue by DarioS** [ryantibs/best-subset#2]
It seems that the shared object has been created on another operating system and is not compatible with the operating system which I'm using.

```
* installing *source* package ‘bestsubset’ ...
** libs
make: Nothing to be done for 'all'.
installing to /dskh/nobackup/biostat/Bioconductor/bestsubset/libs
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘bestsubset’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/dskh/nobackup/biostat/Bioconductor/bestsubset/libs/bestsubset.so':
  /dskh/nobackup/biostat/Bioconductor/bestsubset/libs/bestsubset.so: invalid ELF header
```

The operating system's details are:

```
Distributor ID: Debian
Description:    Debian GNU/Linux 8.9 (jessie)
Release:        8.9
Codename:       jessie
```

How about improving the README file? It has barely any instructions or details about which platforms best-subset works on.

**Comment by ryantibs** [comment]
I removed the so and o files from the src folder.  They shouldn't be there
(they are a result of R's compilation process).  You can try reinstalling
now.

**Comment by DarioS** [comment]
Installation of bestsubset completed successfully.
