### ISSUE TITLE
Incorrect specification of bounds for n<p case

### ISSUE THREAD

**Issue by tanmaysatpathy** [ryantibs/best-subset#24]
Hi, 

for the n<p case, you have defined. 
zeta.bd =colSums(apply(abs(x),1,sort,decreasing=True)[1:k,,drop=F])*bigM

As per equation 17 here: https://arxiv.org/pdf/1507.03133.pdf
it should be max(apply(abs(x),1,sort,decreasing=True)[1:k,,drop=F])*bigM

**Comment by ryantibs** [comment]
Closed by #25.
