### ISSUE TITLE
install best-subset package on windows 7

### ISSUE THREAD

**Issue by JosHageman** [ryantibs/best-subset#3]
I'm unable to install the package on my win7 machine. I have installed gurobi 32 and 64 bits, but initially tried everything 64 bit. I also installed the gurobi package.

It seems as if the best-subset package want the Gurobi package to be present for 32 AND 64 bits?

output install with 32 or 64 bit Gurobi package:

> install_github(repo="ryantibs/best-subset", subdir="bestsubset")
Downloading GitHub repo ryantibs/best-subset@master
from URL https://api.github.com/repos/ryantibs/best-subset/zipball/master
Installing bestsubset
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/hagem011/AppData/Local/Temp/RtmpqiHNTk/devtools1dc50e6ac5/ryantibs-best-subset-2f7d518/bestsubset"  \
  --library="C:/Program Files/R/R-3.4.0/library" --install-tests 

* installing *source* package 'bestsubset' ...
** libs

*** arch - i386
C:/RBuildTools/3.4/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c matrixcomps.c -o matrixcomps.o
C:/RBuildTools/3.4/mingw_32/bin/gcc -shared -s -static-libgcc -o bestsubset.dll tmp.def matrixcomps.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/i386 -lR
installing to C:/Program Files/R/R-3.4.0/library/bestsubset/libs/i386

*** arch - x64
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c matrixcomps.c -o matrixcomps.o
C:/RBuildTools/3.4/mingw_64/bin/gcc -shared -s -static-libgcc -o bestsubset.dll tmp.def matrixcomps.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/x64 -lR
installing to C:/Program Files/R/R-3.4.0/library/bestsubset/libs/x64
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error : package 'gurobi' is not installed for 'arch = i386'
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Program Files/R/R-3.4.0/library/bestsubset'
* restoring previous 'C:/Program Files/R/R-3.4.0/library/bestsubset'
Installation failed: Command failed (1)
> install.packages("C:/gurobi751/win32/R/gurobi_7.5-1.zip", repos = NULL, type = "win.binary")
package ‘gurobi’ successfully unpacked and MD5 sums checked
> install_github(repo="ryantibs/best-subset", subdir="bestsubset")
Downloading GitHub repo ryantibs/best-subset@master
from URL https://api.github.com/repos/ryantibs/best-subset/zipball/master
Installing bestsubset
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/hagem011/AppData/Local/Temp/RtmpqiHNTk/devtools1dc373a6d1b/ryantibs-best-subset-2f7d518/bestsubset"  \
  --library="C:/Program Files/R/R-3.4.0/library" --install-tests 

* installing *source* package 'bestsubset' ...
** libs

*** arch - i386
C:/RBuildTools/3.4/mingw_32/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O3 -Wall  -std=gnu99 -mtune=core2 -c matrixcomps.c -o matrixcomps.o
C:/RBuildTools/3.4/mingw_32/bin/gcc -shared -s -static-libgcc -o bestsubset.dll tmp.def matrixcomps.o -Ld:/Compiler/gcc-4.9.3/local330/lib/i386 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/i386 -lR
installing to C:/Program Files/R/R-3.4.0/library/bestsubset/libs/i386

*** arch - x64
C:/RBuildTools/3.4/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-34~1.0/include" -DNDEBUG     -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c matrixcomps.c -o matrixcomps.o
C:/RBuildTools/3.4/mingw_64/bin/gcc -shared -s -static-libgcc -o bestsubset.dll tmp.def matrixcomps.o -Ld:/Compiler/gcc-4.9.3/local330/lib/x64 -Ld:/Compiler/gcc-4.9.3/local330/lib -LC:/PROGRA~1/R/R-34~1.0/bin/x64 -lR
installing to C:/Program Files/R/R-3.4.0/library/bestsubset/libs/x64
** R
** preparing package for lazy loading
Error : package 'gurobi' is not installed for 'arch = x64'
ERROR: lazy loading failed for package 'bestsubset'
* removing 'C:/Program Files/R/R-3.4.0/library/bestsubset'
* restoring previous 'C:/Program Files/R/R-3.4.0/library/bestsubset'
Installation failed: Command failed (1)

**Comment by zhan-gao** [comment]
Hi @JosHageman, I think the solution in issue #5 can help.

**Comment by JosHageman** [comment]
This solved the issue!
